---
enable_pixeltopath: false
vtracer_version: "0.6.4"
vtracer_binary_url: "https://github.com/visioncortex/vtracer/releases/download/{{ vtracer_version }}/vtracer-x86_64-unknown-linux-musl.tar.gz"
vtracer_checksum: "sha256:FILL_IN_AFTER_DOWNLOAD"
pixeltopath_version: "2.0.0"
pixeltopath_url: "https://github.com/lorrisc/PixelToPath/releases/download/v{{ pixeltopath_version }}/PixelToPath-v{{ pixeltopath_version }}_Linux.tar"
oxipng_binary_url: "https://github.com/shssoichiro/oxipng/releases/latest/download/oxipng-x86_64-unknown-linux-musl.tar.gz"
